version: '3.7'

services:
    update_domain:
        container_name: update_domain
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - TOKEN=${DIGITAL_OCEAN_TOKEN:-<your_digital_ocean_token>}
            - DOMAIN=${DIGITAL_OCEAN_DOMAIN:-<your_digital_ocean_domain>}
            - RECORD_ID=${DIGITAL_OCEAN_RECORD_ID:-<your_digital_ocean_record_id>}
        volumes:
            - <path_to_persistence_directory>:/data # Optional, but recommended
